Logging errors to tmp/

diff --git a/bin/php-build b/bin/php-build
--- a/bin/php-build
+++ b/bin/php-build
@@ -17,6 +17,8 @@
 
 set -e
 
+exec 3<&2
+
 CONFIGURE_OPTIONS="--without-pear \
 --with-gd \
 --with-jpeg-dir=/usr \
@@ -50,6 +52,7 @@ CONFIGURE_OPTIONS="--without-pear \
 --with-readline"
 
 PHP_BUILD_ROOT=$(readlink -f "$(dirname $0)/..")
+TMP="$PHP_BUILD_ROOT/tmp"
 PHP_DEFAULT_INI=
 
 if [ "$1" = "-i" ] || [ "$1" = "--ini" ]; then
@@ -64,7 +67,7 @@ PREFIX=$2
 E_DEFINITION_NOT_FOUND=127
 
 function display_usage {
-    grep '^#/' <"$0" | cut -c4- >&2
+    grep '^#/' <"$0" | cut -c4- >&3
 }
 
 function init {
@@ -111,16 +114,21 @@ function download {
 }
 
 function list_definitions {
-    for definition in "$PHP_BUILD_ROOT/definitions/"*; do
-        echo $(basename "$definition")
-    done
+    {
+        for definition in "$PHP_BUILD_ROOT/definitions/"*
+        do
+            echo $(basename "$definition")
+        done
+    } | sort >&3
 }
 
 function install_package {
     local url=$1
 
-    download $url
-    build_package "$PHP_BUILD_ROOT/source/$DEFINITION"
+    {
+        download $url
+        build_package "$PHP_BUILD_ROOT/source/$DEFINITION"
+    } >&4 2>&1
 }
 
 function trigger_after_install {
@@ -130,7 +138,7 @@ function trigger_after_install {
     echo "Trigger after-install"
     for trigger in "$PHP_BUILD_ROOT/triggers/after-install.d/"*; do
         echo "$(basename $trigger)"
-        "$trigger"
+        "$trigger" 2>&4
     done
 }
 
@@ -163,7 +171,7 @@ function build_package {
             echo "Using $PHP_DEFAULT_INI as php.ini"
             cp "$source_path/$PHP_DEFAULT_INI" "$PREFIX/etc/php.ini"
         else
-            echo "$PHP_DEFAULT_INI not found in $source_path" >&2
+            echo "$PHP_DEFAULT_INI not found in $source_path" >&3
         fi
     fi
 
@@ -232,7 +240,27 @@ function configure_package {
     cd "$backup_pwd"
 }
 
+function build_error {
+    {
+        echo "BUILD ERROR"
+        echo
+        echo "The Log is available here ${LOG_PATH}"
+        echo
+    } >&3
+    
+    cleanup_abort
+}
+
+function cleanup_abort {
+    rm "$PREFIX" -rf
+}
+
 # Here the magic begins.
+
+TIME="$(date "+%Y%m%d%H%M%S")"
+LOG_PATH="$TMP/php-build.$DEFINITION.$TIME.error.log"
+
+exec 4<> "$LOG_PATH"
 
 # Set up the directories needed for the source
 # and the downloaded packages.
@@ -251,7 +279,7 @@ fi
 
 # Check if the requested Definition exists.
 if [ ! -f "$PHP_BUILD_ROOT/definitions/$DEFINITION" ]; then
-    echo "Definition $DEFINITION not found." >&2
+    echo "Definition $DEFINITION not found." >&3
     exit $E_DEFINITION_NOT_FOUND
 fi
 
@@ -260,7 +288,16 @@ fi
 # examples.
 load_plugins "$PHP_BUILD_ROOT/plugins"
 
+echo
+echo "Building $DEFINITION into $PREFIX"
+
+trap cleanup_abort SIGINT SIGTERM
+
+trap build_error ERR
 source "$PHP_BUILD_ROOT/definitions/$DEFINITION"
 
-trigger_after_install
+# After Install Triggers are all executables placed in `triggers/after-install.d`
+#
+trigger_after_install 2>&4
 
+trap - ERR
